name: DhakaCart CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-test:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      # Setup Node.js for frontend & backend
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      # Frontend Install & Test
      - name: Frontend Install & Test
        working-directory: frontend
        run: |
          npm ci
          npm test

      # Backend Install & Test
      - name: Backend Install & Test
        working-directory: backend
        run: |
          npm ci
          npm test

  docker-build:
    name: Build Docker Images
    runs-on: ubuntu-latest
    needs: build-test
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Frontend Image
        run: |
          docker build -t dhakacart-frontend:latest ./frontend

      - name: Build Backend Image
        run: |
          docker build -t dhakacart-backend:latest ./backend


  deploy:
    name: Deploy to Kubernetes
    runs-on: ubuntu-latest
    needs: docker-build
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      # Setup kubectl
      - name: Setup kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'v1.34.0'

      # Copy kubeconfig from secrets (optional) or rely on local kubeconfig
      #- name: Setup Kubeconfig
      #  run: |
      #    echo "${{ secrets.KUBECONFIG }}" > ~/.kube/config

      # Apply Kubernetes manifests
      - name: Deploy Backend
        run: kubectl apply -f kubernetes/deployments/backend-deployment.yaml -n dhakacart

      - name: Deploy Frontend
        run: kubectl apply -f kubernetes/deployments/frontend-deployment.yaml -n dhakacart

      - name: Apply Services
        run: kubectl apply -f kubernetes/services/ -n dhakacart

      - name: Apply Ingress
        run: kubectl apply -f kubernetes/ingress/ -n dhakacart
